/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/pairs": {
    /** Enabled trading instruments */
    get: operations["getPairs"];
  };
  "/api/coherence/status": {
    /** Latest coherence metrics for an instrument */
    get: operations["getCoherenceStatus"];
  };
  "/api/kill-switch": {
    /** Kill switch status */
    get: operations["getKillSwitch"];
    /** Toggle kill switch */
    post: operations["setKillSwitch"];
  };
  "/api/trading/mode": {
    /** Trading mode and OANDA environment */
    get: operations["getTradingMode"];
  };
  "/api/oanda/account": {
    /** OANDA account summary */
    get: operations["getOandaAccount"];
  };
  "/api/oanda/positions": {
    /** Open OANDA positions */
    get: operations["getOandaPositions"];
  };
  "/api/oanda/open-trades": {
    /** Open trades */
    get: operations["getOandaOpenTrades"];
  };
  "/api/oanda/pricing": {
    /** Latest bid/ask pricing */
    get: operations["getOandaPricing"];
  };
  "/api/market-data": {
    /** Historical market data window */
    get: operations["getMarketData"];
  };
  "/api/risk/allocation-status": {
    /** Current portfolio allocation weights */
    get: operations["getAllocationStatus"];
  };
  "/api/ranking/active": {
    /** Session-aware ranking of instruments */
    get: operations["getActiveRanking"];
  };
  "/api/manifold/coeffs": {
    /** Latest manifold coefficients for an instrument */
    get: operations["getManifoldCoeffs"];
  };
  "/api/candles": {
    /** Candle priming endpoint */
    get: operations["getCandles"];
  };
  "/api/authenticity": {
    /** Authenticity diagnostics by instrument */
    get: operations["getAuthenticity"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CoherenceStatus: {
      instrument?: string;
      /** Format: int64 */
      ts_ms?: number;
      coherence?: number;
      stability?: number;
      entropy?: number;
      rupture?: number;
      metrics?: {
        [key: string]: unknown;
      };
    };
    TradingMode: {
      practice_trading_enabled?: boolean;
      auto_trading_enabled?: boolean;
      environment?: string;
    };
    ActiveRanking: {
      /** Format: int64 */
      now_ms?: number;
      sessions?: string[];
      items?: ({
          instrument?: string;
          is_open?: boolean;
          near_close?: boolean;
          score?: number;
          flow_m5?: number;
          coherence?: number;
          stability?: number;
          entropy?: number;
          hazard?: number | null;
          repetitions?: number;
          admit?: number;
          direction?: string;
          gate_source?: string;
          regime_min_reps?: number;
          regime_hazard_max?: number;
        })[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Enabled trading instruments */
  getPairs: {
    responses: {
      /** @description List of instruments */
      200: {
        content: {
          "application/json": {
            pairs?: string[];
          };
        };
      };
    };
  };
  /** Latest coherence metrics for an instrument */
  getCoherenceStatus: {
    parameters: {
      query: {
        instrument: string;
        points?: number;
      };
    };
    responses: {
      /** @description Coherence metrics payload */
      200: {
        content: {
          "application/json": components["schemas"]["CoherenceStatus"];
        };
      };
    };
  };
  /** Kill switch status */
  getKillSwitch: {
    responses: {
      /** @description Kill switch state */
      200: {
        content: {
          "application/json": {
            kill_switch?: boolean;
          };
        };
      };
    };
  };
  /** Toggle kill switch */
  setKillSwitch: {
    requestBody: {
      content: {
        "application/json": {
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated status */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Trading mode and OANDA environment */
  getTradingMode: {
    responses: {
      /** @description Trading mode information */
      200: {
        content: {
          "application/json": components["schemas"]["TradingMode"];
        };
      };
    };
  };
  /** OANDA account summary */
  getOandaAccount: {
    responses: {
      /** @description Account info */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Open OANDA positions */
  getOandaPositions: {
    responses: {
      /** @description Positions payload */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Open trades */
  getOandaOpenTrades: {
    responses: {
      /** @description Open trades payload */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Latest bid/ask pricing */
  getOandaPricing: {
    parameters: {
      query: {
        instruments: string;
      };
    };
    responses: {
      /** @description Pricing payload */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Historical market data window */
  getMarketData: {
    parameters: {
      query: {
        instrument: string;
        granularity: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Candle payload */
      200: {
        content: {
          "application/json": {
            candles?: Record<string, never>[];
          };
        };
      };
    };
  };
  /** Current portfolio allocation weights */
  getAllocationStatus: {
    responses: {
      /** @description Allocation weights */
      200: {
        content: {
          "application/json": {
            weights?: {
              [key: string]: number;
            };
          };
        };
      };
    };
  };
  /** Session-aware ranking of instruments */
  getActiveRanking: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Ranking payload */
      200: {
        content: {
          "application/json": components["schemas"]["ActiveRanking"];
        };
      };
    };
  };
  /** Latest manifold coefficients for an instrument */
  getManifoldCoeffs: {
    parameters: {
      query: {
        instrument: string;
      };
    };
    responses: {
      /** @description Coefficients payload */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Candle priming endpoint */
  getCandles: {
    parameters: {
      query: {
        instrument: string;
        granularity?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Candle payload */
      200: {
        content: {
          "application/json": {
            items?: Record<string, never>[];
          };
        };
      };
    };
  };
  /** Authenticity diagnostics by instrument */
  getAuthenticity: {
    parameters: {
      query?: {
        instruments?: string;
      };
    };
    responses: {
      /** @description Authenticity summary */
      200: {
        content: {
          "application/json": {
            instruments?: Record<string, never>[];
          };
        };
      };
    };
  };
}
