"""Isolated options research package for equity and ETF options backtesting."""

from .models import (
    BacktestResult,
    CorporateAction,
    EquityPoint,
    ExitReason,
    FilledOptionPosition,
    LegAction,
    OptionChainSnapshot,
    OptionLeg,
    OptionQuote,
    OptionRight,
    OptionStrategyIntent,
    PackageFill,
    PositionStatus,
    SignalDirection,
    SignalEvent,
    StrategyFamily,
    UnderlyingBar,
)

__all__ = [
    "BacktestResult",
    "CorporateAction",
    "EquityPoint",
    "ExitReason",
    "FilledOptionPosition",
    "LegAction",
    "OptionChainSnapshot",
    "OptionLeg",
    "OptionQuote",
    "OptionRight",
    "OptionStrategyIntent",
    "PackageFill",
    "PositionStatus",
    "SignalDirection",
    "SignalEvent",
    "StrategyFamily",
    "UnderlyingBar",
]
